name: recread
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py
  - obspy=1.2.0
  - bokeh=2.2.3
  - pyproj
  - pandas
  - pytables
  - conda
  - selenium
  - firefox geckodriver