name: recread
channels:
  - conda-forge
  - defaults
  - https://conda.anaconda.org/conda-forge
dependencies:
  - python=3.8.8
  - bokeh=2.3.0
  - pandas=1.2.2
  - scipy=1.6.0
  - h5py=3.1.0
  - hdf5=1.10.6
  - obspy=1.2.2
  - bokeh=2.3.0
  - proj=7.2.0
  - pyproj=3.0.0.post1
  - pytables
  - firefox=86.0
  - geckodriver=0.29.0
  - conda
  - pip
  - pip:
    - jupyter-server-proxy
    - get-gecko-driver==1.3.1
    - selenium==3.141.0
    - tables==3.6.1
    - jinja2==3.0.1
